### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by lzlly** [hriener/ctlsat#1]
When I use cmake to compile the code, I got an erroe:
E:\code\ctlsat\src\Tableau.cpp:111:18: error: 'time' was not declared in this scope
  timestamp=time(0);

**Comment by hriener** [comment]
Note that I am not the author of the source code, but only provide the `CMakeLists.txt` file to build `ctlsat`.
For me, this version compiles under OSX and Linux. I have not tried it on a Windows system.

Based on the error message, you could try to include the header `ctime` ([ref.](https://www.cplusplus.com/reference/ctime/)) in `Tableau.cpp`. However, you may run into other issues afterward.

**Comment by hriener** [comment]
Closed because of inactivity.

**Comment by lzlly** [comment]
> Note that I am not the author of the source code, but only provide the `CMakeLists.txt` file to build `ctlsat`.
> For me, this version compiles under OSX and Linux. I have not tried it on a Windows system.
> 
> Based on the error message, you could try to include the header `ctime` ([ref.](https://www.cplusplus.com/reference/ctime/)) in `Tableau.cpp`. However, you may run into other issues afterward.

Thanks, it works after I include the header ctime and there was no other issue.
